### ISSUE TITLE
Bugged payment

### ISSUE THREAD

**Issue by Vanheden** [ESX-Org/esx_billing#10]
You can bug the payment and get rich within one click you want. Make it so you can't go minus  with invoice. I mean if the player don't have the money he can't pay the invoice.

**Comment by ElPumpo** [comment]
This commit has fixed the issue https://github.com/StockholmCityRP/esx_billing/commit/d052d9804264f6611965e86e658be4f0545b8e0f

**Comment by ElPumpo** [comment]
Fixee, see #12
