### ISSUE TITLE
 How do I import the database?

### ISSUE THREAD

**Issue by HalcongamerYT** [ESX-Org/esx_billing#20]
How do I import the database?

**Comment by mattish91** [comment]
i suppose you have to have a mysql server running for this to work, but there is no way (i found no way) to configure this... and there is not that much of a documentation of how to imoprt stuff in to the database nor how to make the connection there. (im running aproximitly 15 websites from my current computer with mysql installed and ave imported alot of stuff in there. but this config file makes no sense to me without connection details to the actual database server.)
