### ISSUE TITLE
How to fix cheat?

### ISSUE THREAD

**Issue by XvenDeR** [ESX-Org/esx_billing#29]
An cheater raged on server giving everyone insane bills like 4000 for everyone. How do we fix this?

> `1055    steam:11000011706c2b5    steam:11000010f74bedf    player    steam:11000010f74bedf    Best Tiago Menu    10000000
> 
> 1056    steam:11000010f74bedf    steam:11000010f74bedf    player    steam:11000010f74bedf    Best Tiago Menu    10000000`

**Comment by nertigel** [comment]
https://github.com/nertigel/esx_billing enjoy

**Comment by XvenDeR** [comment]
interesting solution, thanks.
