### ISSUE TITLE
Players unable to pay invoices

### ISSUE THREAD

**Issue by mortdudley** [ESX-Org/esx_billing#34]
I'm getting the following error when players try to pay invoices. It worked fine on our previous server however, we did a rebuild with the latest version of ESX. We have the latest version of all the scripts. I have compared it with the working version of our previous scripts but it's all the same word for word as far as I can tell.

> SCRIPT ERROR: @esx_billing/server/main.lua:178: attempt to call a nil value (field 'getBank')
> handler (@esx_addonaccount/server/main.lua:63)
> ref (@esx_billing/server/main.lua:160)
>  (@mysql-async/mysql-async.js:14959)

I've gone through the script a bunch of times and I can't seem to work it out. Any help would be appreciated.

**Comment by ElPumpo** [comment]
You are right

**Comment by mortdudley** [comment]
Further info in case it's helpful - I changed the fxmanifest.lua back to a __resource.lua. We can now pay invoices however, the error in the console mentioned above still remains and we've had multiple reports of players losing large amounts of money from their bank accounts when they have unpaid invoices. We don't have any auto invoice payment scripts on so I haven't been able to track the cause.

**Comment by ElPumpo** [comment]
Wtf why would you ever think that fixes the issue???

**Comment by mortdudley** [comment]
It was a process of elimination. I went through everything I could with no luck and I was all out of other ideas. It can't be a coincidence though that we could all of a sudden start paying invoices one I created the __resource.lua.

FYI, if I revert back to the fxmanifest.lua then we lose the ability to pay invoices again.

**Comment by ElPumpo** [comment]
It's obvious that it does NOT fix the issue at all, and why would you ever think that it would??

**Comment by mortdudley** [comment]
I mean, I think I just answered your question. If you're saying the issues isn't fixed, why did you close the issue?

**Comment by DennisFusha** [comment]
I have the same bug , what's the fix?
