### ISSUE TITLE
Error with esx_billing

### ISSUE THREAD

**Issue by MisterMike99** [ESX-Org/esx_billing#7]
[       297] Error loading script server/main.lua in resource esx_billing: server/main.lua:73: attempt to index a nil value (global 'ESX')
[       313] stack traceback:
[       329] 	server/main.lua:73: in main chunk
[       204] Failed to load script server/main.lua.
[      1297] Started resource esx_billing

can anyone help?

**Comment by RomainLanz** [comment]
Please, run `es_extended` before this resource.
