### ISSUE TITLE
error when loading script esx_billing

### ISSUE THREAD

**Issue by Malviaa** [ESX-Org/esx_billing#9]
Error loading script server/main.lua in resource esx_billing: server/main.lua:73
: attempt to index a nil value (global 'ESX')
stack traceback:
        server/main.lua:73: in main chunk
Failed to load script server/main.lua.
Started resource esx_billing

Anyone know what the problem is?

**Comment by ElPumpo** [comment]
ESX is not properly installed.

**Comment by Kuhicop** [comment]
I have the same problem, installed with git as the install instructions say.
Maybe the install steps are missing something?
